### ISSUE TITLE
Just wanted to say thanks for Zimodem/C64Net

### ISSUE THREAD

**Issue by ukscone** [bozimmerman/Zimodem#1]
Just want to say thanks for making zimodem. I used it for hooking up my Tandy M100 up to a couple of BBS's and it works really well. https://twitter.com/ukscone/status/856233567285899264 I need to put everything on vero board and put it in a nice case though to make it look snazzy too but the s/w works great and especially love the in-prog updating for easy upgrades

**Comment by bozimmerman** [comment]
You are very welcome, sir.  Thanks for the kind words.  
As you might have noticed, the software was designed specifically for use on low resource machines like your Tandy (or my C64).    And since I'm actively developing apps for it, I can manage to keep it relatively well tested and bug free. :)
