### ISSUE TITLE
Prestel / Viewdata Terminal support

### ISSUE THREAD

**Issue by marrold** [bozimmerman/Zimodem#114]
Hi,

Thanks for creating this software! I was wondering if it would be possible to add support for Prestel / Viewdata Terminals. 

There's two main differences between other machines:

1. They operate with a split baud rate, namely 1200 baud down and 75 baud up - I think this might be tricky to implement as the ESPs won't do a split baud rate. Not essential.
2. Rather than enter they use ⌗ which is sent as 0x5F in ASCII - This causes problems when modems etc are expecting an AT command to be terminated with a newline.

Thanks

**Comment by bozimmerman** [comment]
You are correct about #1.. not even sure where you go with that.
You are in LUCK with #2 though!  ATS3 and ATS4 can be set to 0x5f or anything else you like!
