### ISSUE TITLE
RI (Ring Indicate) signal transition to quick

### ISSUE THREAD

**Issue by Mikey351AU** [bozimmerman/Zimodem#118]
While preparing to add the RI line from the ESP12F to the userport I was decided to check that GPIO14 was transitioning with each ring. It was, however it happens so quickly that my logic probe barely registered the transition. I doubt that the C64 would be able to read the transition that quickly. It would probably work best if it held its state for 1s before reverting back to whatever its normal (non ringing) state is.

**Comment by bozimmerman** [comment]
Hmm.. I recently messed around with the ringer code -- can you check it again and report back?
