### ISSUE TITLE
Error during compliation

### ISSUE THREAD

**Issue by vk5ln** [bozimmerman/Zimodem#122]
The most recent work on Zimodem seems to have introduced a compilation error in zcommand.ino for me;

C:\Users\michaelc\Documents\Arduino\zimodem\zcommand.ino: In member function 'ZResult ZCommand::doSerialCommand()':
C:\Users\michaelc\Documents\Arduino\zimodem\zcommand.ino:2874:50: error: cannot pass objects of non-trivially-copyable type 'class String' through '...'
                     serial.printf("%d%s",res,EOLN);
                                                  ^

exit status 1

Compilation error: cannot pass objects of non-trivially-copyable type 'class String' through '...'

My previous code pull was done sometime in January 2024 and it is compiling fine.

**Comment by bozimmerman** [comment]
Thanks -- for some reason your compiler is better than mine, as I neither spotted this, nor have I run into a crash related to it.
