### ISSUE TITLE
Uploading Binary files

### ISSUE THREAD

**Issue by djchez01** [bozimmerman/Zimodem#126]
Bo, does uploading of binary files via Xmodem to a BBS work? I am trying to help folks do this using the wifi modem connected to a Tandy Color Computer via an RS232 pak, but it does not seem to work. One suggestion that's been made is that zimodem possibly has the word length stuck at 7 rather than 8 when transferring. I've seen older reports of Ymodem not working for uploads of binary, but I am not sure this was ever resolved. Thanks in advance for your help.

**Comment by dabonetn** [comment]
Make sure you aren't connecting using the atdt command, that enables telnet handling, and causes binary corruptions on machines that aren't telnet aware. Use atd instead.

**Comment by bozimmerman** [comment]
Yea, there's something weird being done, as I use X-Modem quite often.
