### ISSUE TITLE
SPI input enhancement 

### ISSUE THREAD

**Issue by ghhann** [bozimmerman/Zimodem#127]
First congratulations on your excellent work in this project.  

Esp32 can be put into slave mode and can handle SPI 
Communications.  I’m thinking of an adsfruit airlift where they add WiFi to a project for IOT packets. 

The new UNO also has an esp32 chip on board. 

I was wondering if you could add SPI communication to your project.  

I’m thinking of the commanderx16 project that has available and other new retro computers. 

All my best

**Comment by bozimmerman** [comment]
I think I would need hardware with either some sort of universal SPI Port (does that exist?), or something already hooked up to SPI.  If you ever see anything like that for retro machines, lmk.
