### ISSUE TITLE
does not support SGA 

### ISSUE THREAD

**Issue by arcadeshopper** [bozimmerman/Zimodem#128]
Telnet suppress go-ahead not supported by this firmware 
![PXL_20240404_170151650 MP](https://github.com/bozimmerman/Zimodem/assets/34459018/0a4df00e-518e-436a-bb5c-8f15f95a40ba)

**Comment by bozimmerman** [comment]
If the remote BBS supports Telnet codes, then try using ATD thekeep.net instead of ATDT.  ATDT forces the modem to intercept telnet codes.  Future versions won't do this by default.
