### ISSUE TITLE
ESP32 - build successful but after reboot does not go beyond Init Complete

### ISSUE THREAD

**Issue by theshinyknight** [bozimmerman/Zimodem#130]
I was successful in compiling the INO file and the ESP32 module does show on the serial monitor the boot text, but does not accept any command after

`ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
Zimodem 4.0.1 firmware starting initialization
Baud 1200, Deque constant now: 4
Config changing to 134217756.
Deque constant now: 4
Config changed.
Resetting...
Init complete.
`

I am using a standard ESP32 dev module from Amazon; with default settings except the speed reduced to 80MHz.

**Comment by bozimmerman** [comment]
Hmm.. so, the firmware opens two serial ports on the ESP32.  One is the debug port, which you are seeing, and the other is the 'user' port, where AT commands can be entered.  I suspect you just need to switch which serial port you are monitoring. (or monitor both!)
