### ISSUE TITLE
Failing build fix

### ISSUE THREAD

**Issue by DanielOaks** [bozimmerman/Zimodem#131]
Hey there! I've tried to compile this for my own lil esp8266 wifi modem build, and compilation with the latest Arduino IDE failed because [this function](https://github.com/bozimmerman/Zimodem/blob/master/zimodem/zcommand.ino#L347) `ZCommand::reSaveConfig` doesn't return a value at the end of the function. Adding `return false` at the end of the function (after [this line](https://github.com/bozimmerman/Zimodem/blob/master/zimodem/zcommand.ino#L415)) seems to let it compile correctly.

Thanks for the amazing project mate!!

**Comment by bozimmerman** [comment]
Thanks Daniel.
