### ISSUE TITLE
Hardware flow control

### ISSUE THREAD

**Issue by Sassa0** [bozimmerman/Zimodem#16]
Hello Bo,
Excuse me if my question is dumb.

ESP8266 UART provides pins for hardware flow control : RTS is IO15 and CTS is IO13.
It is possible to enable it in arduino : http://www.esp8266.com/viewtopic.php?f=27&t=8560

Why not use it ? (or at least use these pins in order to be able to enable it later ?)

Actually I see that zimodem use pin 4 for CTS (to computer's RTS) and 5 for RTS (to computer's CTS).

**Comment by bozimmerman** [comment]
Nah, it's not a dumb question.

The pins you mentioned don't exist on the ESP-01 packages, which was the first package that this firmware was implemented for.   When the ESP12E/NodeMCU package was added, the closest pins to those used for the ESP-01 were used, and the Arduino libraries didn't even support flow control, so it was all done from scratch anyway, so they ended up at 4 & 5.  

To your last question, YES! The firmware supports changing the pin assignments in many different ways.  You can tinker with the hard-coded defaults in the #defines near the top of zimodem.ino.  You can also do it through the AT-command set with AT46 through AT57, and then saved with AT&W.
