### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by drencorxeen** [bozimmerman/Zimodem#19]
I am getting some build errors that weren't happening two months ago.
[builderrors20180522.txt](https://github.com/bozimmerman/Zimodem/files/2028282/builderrors20180522.txt)

**Comment by mrgw454** [comment]
I contacted Bo directly about this compile issue a few days ago in email.  He was very quick to respond and is looking into it.

**Comment by drencorxeen** [comment]
That is good to know.
I am using the current stable ESP8266 and Arduino IDE 1.8.5

So hopefully that helps.

**Comment by bozimmerman** [comment]
You should be all good now -- sorry about that.  Hopefully in a few weeks I'll have zmodem actually working and we can find something interesting to do with it.. in the meantime, I apologize for breaking your builds.
