### ISSUE TITLE
Wemos Nodemcu bugs

### ISSUE THREAD

**Issue by soydemadrid** [bozimmerman/Zimodem#20]
Hi I hope you can help. I've flashed a few NodeMCU LUA type wemos dev boards and most work ok but I seem to have a few bugs.

One board works but when I type it repeats characters and double echos the commands back to me. Or inserts strange characters amongst the legit ones. When I hit enter the at commands work the same, just it is hard to see what I've typed correctly or what input I've done.

On this particular board it only seems to have this issue when set to the default 1200 baud. If I ATB57600 or some other board it inputs and types fine...

Do you know of anything that may cause this or how I can fix it? Or is the dev board just messed up (though seems odd it works ok at other bauds).

I tried doing the over the air firmware update too but that hasn't helped either.

**Comment by bozimmerman** [comment]
So, you have several identical units, and the problems appear on some of them, but not all?  If that's the case, then my guess is that you got some bad units.    I can't imagine what would make the baud rate unreliable at low levels, but not at higher ones, but that's definitely a function of the underlying libraries and hardware.  You might try putting some other firmware on the bad unit and see if it still can't do 1200 baud.
