### ISSUE TITLE
Pet2asc

### ISSUE THREAD

**Issue by dillera** [bozimmerman/Zimodem#22]
Not really an issue as much as a question- I'm trying to use this w/ Atari and i can't quite follow in the code if it's doing the petacsii conversion by default or not. What triggers the conversion? I'm getting nothing but strange chars on my Mac as well as the atari when connected.

**Comment by bozimmerman** [comment]
ASCII is the default mode.  The only ways to get PETSCII translation is either with AT&P1 or by including the "P" in another command (ATD, ATC, etc..).  Since you are using ATARI, as long as you keep your finger away from the "P" key, you should be good.
