### ISSUE TITLE
up9600 hack on nodemcu

### ISSUE THREAD

**Issue by soydemadrid** [bozimmerman/Zimodem#23]
Hi Bo, I wondered if you could help.

I have a NodeMCU ESP8266 flashed with zimodem hooked up to a userport on my C64.

It works great and I can use it with user port at 2400 but can't seem to get the up9600 hack working. I'm not sure how to set this up but I've tried setting the baud to 9600 first then setting the modem to UP9600.

At that point I can't type any at commands or anything in at all though so I just have to switch back to User Port on the lower baud again. Thanks for any help with this. :)

**Comment by bozimmerman** [comment]
You just did things in the wrong order my friend.
When the computer is started, the modem defaults to 1200 baud.
Load up your terminal program and set it to 1200 baud also.
Then go into terminal mode and enter:
ATB9600
 -- Now the modem is expecting 9600 baud.  Go back to your terminal programs settings menu and change the terminal program baud rate to 9600.  Some terminal programs will also require you to change the modem type to UP9600.  Once you've done that, go back into terminal mode and you should be good.

**Comment by soydemadrid** [comment]
Hi Bo, sorry to reopen this but for some reason that doesn't want to work for me.

I can type AT commands no problem and match up the correct bauds needed to communicate with the modem. But when I select the modem type as User Port it only allows 2400.

If I choose instead UP9600 as the modem type (first setting the baud rate of the modem to 9600) then I can't type anything. I've set the baud first via User Port modem type to 9600, then switched to UP9600 but that is where I'm getting stuck...

Thanks again for any help.

**Comment by bozimmerman** [comment]
OK, well, if you are doing things in the proper order, then the only possibility remaining is that the UP9600 pins on the user port are incorrect?

**Comment by soydemadrid** [comment]
Hi thanks. I figured there must be a pin or connection that might need bridging or such. Which pin on the user port is for up9600 detection and where should it be rooted?

I haven't been able to find any reference to a UP9600 pin online... Thanks again for the help :)

**Comment by bozimmerman** [comment]
Hi.  I'm afraid I'm not really sure about the hardware side.  You've gone beyond my expertise.  However, looking at my own modem schematics, that looks right.

UP9600 interferes with Burst Mode on the Commodore 128.  So if you do this, you won't be able to use any disk drives with the C128 that have Burst Mode, such as the 1571, 1581, or CMD drives (not sure about uIEC).  This is why our own modem has jumpers for UP9600 so that C128 users can turn it off.

**Comment by soydemadrid** [comment]
Hi thanks Bo I'll give it a try. So if I want to use C128 and I don't bother with UP9600 and just use normal User Port setup without extra UP9600 wiring will the C128 still run faster than 2400 or is User Port always maxed out at 2400 baud?
