### ISSUE TITLE
Zimodem firmware on nodeMCU?

### ISSUE THREAD

**Issue by editouch** [bozimmerman/Zimodem#27]
Hi everyone,
I'm interested in building a serial modem that allows me to transfer files from an old mac classic to midern conputer on my LAN.

I have a couple of questions:

A - can I load zimodem firmware on a nodeMCU device? 
B - once configured can I us the modem to perform a PPP connection to a pppd daemon on a pi3? This way I'll enjoy a full tcp/ip session and trasfer files directly on the pi3 (or elsewhere on the LAN) via ftp

Thanks in advance

Marco

P.s. sorry if this sounds as a stupid question but I'm quite a newbie

**Comment by bozimmerman** [comment]
A) Yes, the esp12e is supported.  One of the pin assignments is different than the 8266, but yes.
B) I have no idea what you mean, but I think no.  The modem maintains its own tcp/ip stack -- that's kinda the whole point of the project, to push the socket work off the computer to the ESP device.
