### ISSUE TITLE
1200/75 baud standard

### ISSUE THREAD

**Issue by soydemadrid** [bozimmerman/Zimodem#32]
Hi I just wondered if zimodem supports the 1200/75 baud standard?

Can it connect to services that used to use modem's such as these: http://www.computinghistory.org.uk/det/11414/Protek-JCB01-1200-75-Modem/

Thanks for any help :)

**Comment by bozimmerman** [comment]
I doubt it.  Zimodem doesn't implement it's own RS232 standard, but just uses the built-in uart of the 8266 and ESP32.  So it supports whatever those uarts support.
