### ISSUE TITLE
ATW not showing all networks

### ISSUE THREAD

**Issue by neufena** [bozimmerman/Zimodem#34]
The ATW (or AT+CONFIG) command does not show all networks, just a selection of them.  Is there specific types of routers or configs that the software will not work with?  All routers in range are in b/g or n modes and are 2.4ghz

**Comment by bozimmerman** [comment]
The firmware shows every access point that the firmware and the official ESP libraries return.  So, if some are missing, there's nothing the firmware can do about it.  You might check forums regarding your specific hardware.
