### ISSUE TITLE
cts problem...

### ISSUE THREAD

**Issue by soydemadrid** [bozimmerman/Zimodem#35]
Hi I built a fresh binary in arduino following your steps for a nodemcu 12E...

I edited the firmware code slightly to use  define RS232_INVERTED 0 just so I can plug it in via serial to a PC and type without using the C64 inverted signals.

I've got a strange issue though. The firmware seems to work great other than CTS...

When I type each letter takes 10 seconds to appear. So typing AT+CONFIG is really unresponsive and takes ages!! It does work though but like I say really slow.

As soon as I just unplug the CTS jumper on the board, everything springs in to life and I can type and it is all fast and punchy!

I then of course can't enable rts/cts without it crashing, but even when it is really slow with CTS plugged in I still can't enable rts/cts from at+config menu either.

Any ideas what I've done wrong or why it is running so slow with cts connected?

Thanks for any help at all :)

**Comment by bozimmerman** [comment]
Dude, I feel awful that I missed this.  Are you still there?  It sounds to me like the CTS signal is also incorrect, and its default may be need to be swapped LOW/HIGH around.
