### ISSUE TITLE
Building with proper ESP8266 libraries.

### ISSUE THREAD

**Issue by allenhuffman** [bozimmerman/Zimodem#36]
I need help with how to get ESP8266 libraries that will build non-crashing Zimodem. The one from Boards Manager seems to have issues, and I’m unclear on how I can use the newer dev code. Or, it could be an issue with the current Arduino IDE. Any insight would be appreciated.

**Comment by bozimmerman** [comment]
I'm afraid there isn't enough information here to even make an educated guess.  
Have you checked the README regarding building?
