### ISSUE TITLE
Will not connect to WPA-Enterprise wifi

### ISSUE THREAD

**Issue by quentinnuk** [bozimmerman/Zimodem#40]
Using this software embedded in a Retro Wifi SI, it is not possible to connect to Enterprise-WPA wifi with 802.1x RADIUS authentication using username and password. It would be a useful feature if it could.

Thanks

**Comment by bozimmerman** [comment]
I'm afraid I'm a slave to whatever the ESP libraries support in that respect.  Implementing new security protocols is way outside my wheelhouse I'm afraid. :(
