### ISSUE TITLE
Suggestion: Enhanced phonebook and ping functionality

### ISSUE THREAD

**Issue by mczero80** [bozimmerman/Zimodem#42]
I don't know if it is ok to suggest features under the 'issues' tab, but those are some features that would be nice:

1. An enhanced phonebook with BBS names. Often I don't know which hostname belongs to which bbs.
2. Ping functionality. To check if a IP or hostname responds. I don't know if that works, but automatic pinging all phonebook entries to check which BBSs are online would be nice, too! 

I love Zimodem. Really nice to have it! Thank you.

**Comment by bozimmerman** [comment]
It's perfectly fine!

**Comment by bozimmerman** [comment]
a 'notes' field has been added to the phonebook in the latest src.

**Comment by bozimmerman** [comment]
Ping added.  This is all done now.

**Comment by Biker1bob** [comment]
This is great stuff Bo, thanks so much.
