### ISSUE TITLE
Manual answer with ata command doesn't raise CD line.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#45]
If the bbs host is enabled, and ats0=0 is issued, answering the call with the ata command does connect, but doesn't raise the carrier detect signal.

Enabling auto answer (i.e. ats0=0), results in the connection occurring automatically, and the carrier detect signal being asserted.

**Comment by dabonetn** [comment]
Added a pull request with a fix.

**Comment by bozimmerman** [comment]
Ah, just saw this .. that is a loophole, thanks!
