### ISSUE TITLE
up9600 cc65 ser driver?

### ISSUE THREAD

**Issue by ssuukk** [bozimmerman/Zimodem#48]
Hi Bo,

Have you by any chance created a ser driver for cc65 that uses up9600? I tried it, the driver loads ok and detects the hardware in INSTALL routine, but then hangs when trying to do RSOUT (cc64 PUT). Debugging it is a major PITA and I lost my hope already. But maybe you've already have such ser driver on hand?

**Comment by bozimmerman** [comment]
Sorry, no .. never messed with cc65.
