### ISSUE TITLE
Suggestion: Add fixed ip settings.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#50]
I'm not seeing anyway to define a fixed ip/gateway/dns.
Is this possible to add in the future?

**Comment by bozimmerman** [comment]
I'll see what I can do.

**Comment by bozimmerman** [comment]
Yea, that looks pretty straight forward... it'll be in the next rev.

**Comment by bozimmerman** [comment]
This is now done.  If you build your own firmware: enjoy.  If you are a OTA update user, it may be a few weeks before I can give the new rev a good shakedown, and I might add another feature or two as well.
