### ISSUE TITLE
Feature Suggestion: Default new phone book entries to use current settings.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#56]
It would be nice , if you are adding new phone book entries to not have to remember to change flow control on every entry. (Same with enabling BBS mode).

Maybe global defaults flags that could be set?

**Comment by bozimmerman** [comment]
BBS mode and your flow control settings should be saved with the at&w config file right now.  Is something wrong?

**Comment by dabonetn** [comment]
Using the config menu, if you add a entry it defaults to no flow control.
What I'd like is that it checks the current and applies that to the new entry.
Same with bbs mode in the config menu.

**Comment by bozimmerman** [comment]
This is done in 3.6, but the setting have to be what you entered at+config with.
