### ISSUE TITLE
Feature Suggestion: Busy string.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#59]
Is there a way to respond to another incoming connection while connected with a text string?

I.e. max listeners is 2, if listener 0 is active then 1 automatically responds with the busy message and then auto disconnects.

Like "I'm sorry the bbs has another user currently, please call back later."

**Comment by bozimmerman** [comment]
Yea, technically it tried to send the word BUSY, but socket flush just doesn't work, so the other side doesn't even get it before the socket is closed.  I know what I have to do: create a que of existing connections that need to be closed at a later time.  I just need to do it.

SO! Thanks for the reminder!

**Comment by dabonetn** [comment]
What about leaving it open until a character is received back, or until 5 seconds is reached?

**Comment by bozimmerman** [comment]
Just checked this fix in.  Also made the msg configureable.
