### ISSUE TITLE
Online Update AT&U6502

### ISSUE THREAD

**Issue by ILAHWWINC** [bozimmerman/Zimodem#6]
The command is working bur will update to 2.8.
Is it possible to make 2.9 working or to make a selection available.

**Comment by bozimmerman** [comment]
So, two things:
First: 2.9 is still in testing.  I will definitely release it when I believe it is stable.
Second: 2.8 distribution had a bug! It was set for a 512K ESP-01, which cannot be upgraded. :( If you do ATI you will see it says the total size is 512K.  This means that, for 2.9, you will need to upgrade manually -- the AT&U will not work inside 2.8.
