### ISSUE TITLE
Issue on ESP8266 NODEMCU

### ISSUE THREAD

**Issue by pyr0hax** [bozimmerman/Zimodem#64]
With the latest build I am having an issue where after flashing, it will not take any commands.

![Capture](https://user-images.githubusercontent.com/77932967/119726779-c9229200-be71-11eb-960c-2189756d4cbc.PNG)

**Comment by dabonetn** [comment]
I had the same issue on one of mine, I just selected full erase when writing the sketch again and it worked after that.

**Comment by pyr0hax** [comment]
> I had the same issue on one of mine, I just selected full erase when writing the sketch again and it worked after that.

I am going to ask you a very stupid question. How do you do a full erasure on arduino ide as I am using the ino files to upload to the esp8266? I did a quick google search but did not find anything useful.

**Comment by pyr0hax** [comment]
> I had the same issue on one of mine, I just selected full erase when writing the sketch again and it worked after that.

Lol I found it. Thanks. Going to try this now and see what happens

**Comment by discoball78** [comment]
I'm seeing the same issue here, using NodeMcu V3

![ERROR](https://user-images.githubusercontent.com/36756086/121350946-977bf180-c96e-11eb-8347-7922becda649.png)

Have tried using erase settings to no avail:

![sett](https://user-images.githubusercontent.com/36756086/121351141-cd20da80-c96e-11eb-887e-258bf9aa51d6.png)

**Comment by bebrown** [comment]
Same issue here. Sometimes it is Exception 0, other times Exception 28.

I have tried erasing the flash. Tried a different ESP8266 module.

Setup is: Mac OS Big Sur, Arduino 1.8.13, board manager esp8266 3.0.0, ZiModem 3.6.3

**Comment by omiq** [comment]
Same, with both a commercial C64wifi adapter and my esp8266 boards, and both the latest and the specified versions of Arduino IDE. I found some older firmware that works but I would rather get this going as it is more feature-rich

```--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (28):
epc1=0x4000bf70 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000014 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffde0 end: 3fffffc0 offset: 0190
3fffff70:  4020c360 3ffef968 3ffef964 3fff0c48  
3fffff80:  3fffdad0 00000000 3ffef5ec 40206304  
3fffff90:  3fffdad0 00000000 3ffef900 4020506a  
3fffffa0:  feefeffe 00000000 3fff0c34 4020ab20  
3fffffb0:  feefeffe feefeffe 3ffe8614 40100ca1  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------⸮⸮⸮
```

**Comment by dabonetn** [comment]
Which ESP8266 lib is everyone using?

I'm still on 2.7.4

**Comment by bozimmerman** [comment]
Again, thanks to Dabo for figuring out that the head revision of the 8266 libs is no longer safe to use.  I've updated the README with his recommended rev.
