### ISSUE TITLE
Adding phonebook entry defaults to echo on for the entry.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#66]
3.6.3, adding a phonebook entry is automatically turning on local echo for keypresses.

This should be off as a default.

**Comment by bozimmerman** [comment]
How are you adding a phonebook entry?  There are several ways...

**Comment by bozimmerman** [comment]
I was unable to reproduce this.
What I tried:
atp"1111111=coffeemud.net:23"
Then listed with atp0 and observed no 'e' flag.
Then did atd1111111 to connect, and noted that there was no key echo.
