### ISSUE TITLE
Leds

### ISSUE THREAD

**Issue by Gabeki17** [bozimmerman/Zimodem#67]
How do leds work?

Including the built in one. So in total 4 leds.

I am curious about their function and behavior.

**Comment by dabonetn** [comment]
Here's a link to a basic circuit you need to wire it up using a wimos-d1 mini esp8266 module.

[https://github.com/dabonetn/ZimodemESP8266Leds/blob/master/Basic%20Schematic.pdf](url)

**Comment by dabonetn** [comment]
When then pins connected to the leds go low (active) then the leds light up.

**Comment by bozimmerman** [comment]
Thanks Dabo!
