### ISSUE TITLE
GPIO_NUM_0 pin conflict

### ISSUE THREAD

**Issue by heneault** [bozimmerman/Zimodem#69]
It seems GPIO_NUM_0 is used for both PIN_FACTORY_RESET and DEFAULT_PIN_WIFI

**Comment by dabonetn** [comment]
The DEFAULT_PIN_WIFI is only used when you have LEDs enabled, and the design that currently uses that is based on the esp8266, so the PIN_FACTORY_RESET doesn't apply to that build.

**Comment by heneault** [comment]
I was considering using LEDs with an esp32. This is why I saw this.

**Comment by dabonetn** [comment]
I would just pick a different open pin on the esp32, on the 8266 choices are a bit scarce. Maybe if you also provide a sample circuit, we could have different default pins for the 8266/esp32.
