### ISSUE TITLE
Zimodem ouptuts weird numbers instead of "[LINE BUSY]" message.

### ISSUE THREAD

**Issue by ufud-org** [bozimmerman/Zimodem#71]
If I understand correctly, Zimodem will output a "[LINE BUSY]" message and hang up if there is already an incoming connection active and another client tries to connect via telnet. However, there seems to be a bug causing the output of numerous "3" characters instead of the message. Then the firmware hangs up, as is expected. (see attached screenshot).  

![HMp0_SQU jpg large](https://user-images.githubusercontent.com/42338309/125273656-73188980-e30d-11eb-9986-b8760de81927.jpg)

**Comment by bozimmerman** [comment]
Hmm.. 3 is the NO CARRIER code, but I don't think that's what's happening.  I recently added the ability to customize the busy message, and now I'm wondering if some subsequent change broke that...
Thanks, will definitely look into this!

**Comment by bozimmerman** [comment]
Fixed in 3.6.4 -- thanks for this report.

**Comment by f4grx** [comment]
Thanks for the fix, the reported screnshoot is actually mine :)
