### ISSUE TITLE
Just a binary question

### ISSUE THREAD

**Issue by Gabeki17** [bozimmerman/Zimodem#73]
Is D4 the DCD port on the ESP8266?

Also if there is a clean wiring diagram I could use? :)

Thank you!

Regards,
Gáébor

**Comment by bozimmerman** [comment]
I assume you are using a NodeMCU style package (as opposed to the ESP-01).
So, yes, D4 is GPIO2 on that package, and is the default DCD pin in Zimodem.

**Comment by bozimmerman** [comment]
Oh, to your question, I'm afraid I don't have a schematic for that package... we have one for the ESP32, and one for the ESP-01, but the NodeMCU we do not.  I do recall it is very similar to the StrikeLink design, with DCD added.  You might try googling for those build instructions.
