### ISSUE TITLE
Not really an issue it is more a confusion triggered question

### ISSUE THREAD

**Issue by Gabeki17** [bozimmerman/Zimodem#76]
Hello,

I am now using this brilliant modem since 1-2 months.

Thank you very much for all you did!

I did not buy, but have built my own. 

It works very nice on the C64 now!

And then I run into your blog, where you have mentioned that this modem also works on the VIC-20!

http://ode2commies.blogspot.com/2017/09/

This have really cought my attention!

The VIC-20 has a bit different user port.
Because of this I was not brave enough to plug it in.

I did see that you have added two jumpers.
One is even having a lebel; "C64"

One is between M & 5
Other is between BC & 7
Also t L is connected to 6

What was the reason for this If I may ask?

I meen I understand that this is only usefool for the C64. (To enable 9600 baud or might be even higher)
But will it damage the VIC-20?
Should I build in this two switches/jumpers in and always open the connection whe using on the VIC-20?
Or is it because of other computers like the C128 or the +4?

I have read all the internet but failed to find a proper wiring diagrm for the VIC-20.

Thank you very much for your help in advance!

With regards,
Gábor Zoltán

**Comment by bozimmerman** [comment]
The jumpers are to enable and disable UP9600 support.  It is necessary to disable it for the Commodore 128.  It is optional on all other machines.
