### ISSUE TITLE
Latest commit won't compile for ESP8266

### ISSUE THREAD

**Issue by lodger-c64** [bozimmerman/Zimodem#77]
When compiling the latest commit, I get the following error in 'proto_hostcm.ino' for ESP8266 compiles:

In file included from /home/nhaede/.arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,
                 from /home/nhaede/.arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,
                 from /home/nhaede/.arduino15/packages/esp8266/hardware/esp8266/2.7.1/cores/esp8266/Arduino.h:32,
                 from sketch/zimodem.ino.cpp:1:
/home/nhaede/.arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: section attribute not allowed for 'opt'
   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))
                                                                                                                                  ^
/home/nhaede/src/Zimodem/zimodem/proto_hostcm.h:17:9: note: in expansion of macro 'PROGMEM'
   } opt PROGMEM;
         ^
In file included from /home/nhaede/src/Zimodem/zimodem/proto_hostcm.ino:2:0:
proto_hostcm.h:21:33: error: section attribute not allowed for 'sumchar'
   const char *sumchar PROGMEM = "ABCDEFGHIJKLMNOP";
                                 ^
exit status 1
section attribute not allowed for 'sumchar'

**Comment by bozimmerman** [comment]
should be fixed now
