### ISSUE TITLE
Feature request - Make atdt not dial using telnet protocol as a option.

### ISSUE THREAD

**Issue by dabonetn** [bozimmerman/Zimodem#81]
Can we get a compile or runtime config option for atdt not to be treated as telnet dialing?

This would fix compatibility with older terminals that assume atdt as the dial command, vs atd.

Thanks!

**Comment by dabonetn** [comment]
Or swap it to atdn instead of atdt. (since atdl is the command to dial the last dialed number (I know, not implemented)).

**Comment by bozimmerman** [comment]
Adding ability to turn off Telnet support in the Dial command with ATS62=0
