### ISSUE TITLE
Zimodem Stream issue

### ISSUE THREAD

**Issue by barrow29** [bozimmerman/Zimodem#82]
I'm using a Feather HUZZAH esp 8266 board. I got it working for the most part but ran into this issue while trying to test the streaming before building the rest of the board. I was controlling the board via USB and TeraTerm I would open a new Teraterm window and connect to It again over Wi-Fi this worked for the most part but when using the window connected over Wi-Fi, the USB window would not display the text until I had hit enter. In the other direction It worked exactly as I expected it to printing each character on the opposite window as I typed. If anyone knows what I might be missing or why this is happening your advice would be greatly appreciated.

**Comment by barrow29** [comment]
After looking into it I believe this issue is being caused by the terminal programs I have attempted defaulting to "line at a time mode" Is the Zimodem supposed to send a WILL ECHO command when telnet is enabled or would that need to be added in?

**Comment by bozimmerman** [comment]
DO/DON'T are part of the telnet protocol.  By *not* including the flag that turns on Telnet, you will avoid the behavior.

**Comment by bozimmerman** [comment]
Adding a new flag ATS62 to disable the Telnet flag in the Dial command.
