### ISSUE TITLE
Ethernet Support

### ISSUE THREAD

**Issue by marrold** [bozimmerman/Zimodem#83]
I have a vague aspiration to create a ESP32 based modem with _ethernet_ support for use in areas with poor wifi using something like the [WT32-ETH01](https://www.aliexpress.com/item/32300177304.html)

Are there any plans to add Ethernet support to Zimodem? 

Thanks

**Comment by bozimmerman** [comment]
Shouldn't be much of a change -- Get me some hardware and I'd be happy to add it.

**Comment by dabonetn** [comment]
Hey I've got a couple of these laying around, want me to send you one?
