### ISSUE TITLE
Settings for conventional RTS/CTS ESP12E pin assignments

### ISSUE THREAD

**Issue by profdc9** [bozimmerman/Zimodem#84]
My understanding is that the default pin assignments for ESP8266/ESP12E so that the hardware implements RTS/CTS flow control is 

RTS = GPIO13 (connected to CTS of host)
CTS = GPIO15 (connected to RTS of host)

Is this the default of Zimodem?  This is the way I implemented it on the PCB I designed:

https://github.com/profdc9/WifiModem

It seems to be the pinout given in the manual.  I have attached the relevant pages below.  If not, does the pin # on the ATS49 and ATS51 commands refer to the GPIO # or the physical PIN number so that

(GPIO number)
ATS49=15
ATS51=13

(or physical pin #)
ATS49=12
ATS51=13

Thank you for your great firmware,

Dan

![ESP8266EX-pins1](https://user-images.githubusercontent.com/42632420/178102916-8dfca3fb-bf5b-4000-bc02-d93d656e26c7.png)
![ESP8266EX-pins2](https://user-images.githubusercontent.com/42632420/178102917-f1b822e5-f206-45f5-919e-44341cafafb3.png)

**Comment by bozimmerman** [comment]
Hello.
Sorry I took so long to see this.  By now you've answered your own question, built 500 of your modems, taken over the world, got bored, moved on, and forgotten all this entirely.  My apologies.

Anyway, those would be the GPIO numbers.  

Wish I could send you a reference implementation schematic or something, but we only have one for the ESP-01 and ESP-32.
