### ISSUE TITLE
Exception 9

### ISSUE THREAD

**Issue by mteletin** [bozimmerman/Zimodem#89]
I compiled the code with Arduino 2.0.2 and uploaded on an ESP-12e with success however, immediately after sending any command I get Exception 9 - unaligned address. Any idea on why do I get this? I mean, I understand the problem and what the exception means but... shouldn't this code just compile and run without this issue? Am I using the wrong (too new) Arduino IDE/compiler?
If I enable warnings on the compiler... it's full of them and I can't compile anything.
Any help is appreciated (even suggesting a different SDK to build the code and uploading).

```
C64Net WiFi Firmware v3.7.1
sdk=2.2.2-dev(38a443e) chipid=1451458 cpu@80
totsize=4096k ssize=344k fsize=1907k speed=40m
INITIALIZED
READY.
A
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (9):
epc1=0x402030b0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000007d depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffde0 end: 3fffffc0 offset: 0190
3fffff70:  4020cf10 3ffefbf4 3ffefbf0 3fff0ed4  
3fffff80:  3fffdad0 00000000 3ffef878 40206dbc  
3fffff90:  3fffdad0 00000000 3ffefb8c 4020538c  
3fffffa0:  feefeffe 00000000 3fff0ec0 4020b658  
3fffffb0:  feefeffe feefeffe 3ffe8614 40100e9d  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------J�
C64Net WiFi Firmware v3.7.1
sdk=2.2.2-dev(38a443e) chipid=1451458 cpu@80
totsize=4096k ssize=344k fsize=1907k speed=40m
INITIALIZED
READY.
```

**Comment by mteletin** [comment]
Just compiled it under 1.6.13... same problem with Exception 9. I toyed with compiler options to no avail.

**Comment by mteletin** [comment]
![image](https://user-images.githubusercontent.com/10918175/205150686-b5f0d195-61d0-4790-8d4b-ecb44102afa0.png)

**Comment by ytmytm** [comment]
I had a similar problem today. In my case it was solved by downgrading ESP8266 package (boards) from version 3.0.x to 2.7.4 as suggested in #74

**Comment by mteletin** [comment]
Haven't tried this, but on a different project I had to downgrade and it worked. I assume it's the same with zimodem. Perhaps we can close this one.
