### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by ukscone** [bozimmerman/Zimodem#9]
Just wanted to let you know that i've used your s/w to build a modem for my poquetpc classic (which has a weird connector and uncrosses the rx/tx wires, you need to use a null modem with it's pclink adapter) and it works great. 

https://twitter.com/ukscone/status/906992128642961408
https://twitter.com/ukscone/status/907004002172379136

**Comment by bozimmerman** [comment]
I'm glad you found it useful; thanks for letting me know!
