### ISSUE TITLE
ATM needed

### ISSUE THREAD

**Issue by Biker1bob** [bozimmerman/Zimodem#95]
Need to accept an ATM0/1/2/3/4 command to run a lot of retro software. This was modem Speaker control. It does not have to actually do anything, but it does have to be accept and report an OK.4

BBS software will set ATM=1 and then issue an ATM-0 after a call has been received so that you do not have to hear the communications but you do get to hear the handshake.

**Comment by bozimmerman** [comment]
Thanks!

**Comment by bozimmerman** [comment]
I checked, and ATM0 and ATM1 should already return OK
