### ISSUE TITLE
Add Phone Book Sorting

### ISSUE THREAD

**Issue by Biker1bob** [bozimmerman/Zimodem#96]
Well, this is an actual bug.
Enter 5- 10 phone book entries.  Decide to edit 2 or 10 - and it will then be listed out of order at the bottom of the listing.
See the attached picture.
![20230124_071740](https://user-images.githubusercontent.com/33105915/214291109-7a0605a0-d548-41fd-b894-68b165d2dccf.jpg)

**Comment by bozimmerman** [comment]
done
